fix(vyos): Fix pre-commit script

diff --git a/infrastructure/vyos/scripts/commit/pre-hooks.d/add-container-images b/infrastructure/vyos/scripts/commit/pre-hooks.d/add-container-images
--- a/infrastructure/vyos/scripts/commit/pre-hooks.d/add-container-images
+++ b/infrastructure/vyos/scripts/commit/pre-hooks.d/add-container-images
@@ -3,8 +3,16 @@
 # shellcheck source=/dev/null
 source /opt/vyatta/etc/functions/script-template
 
+if [ "$(id -g -n)" != 'vyattacfg' ] ; then
+    exec sg vyattacfg -c "/bin/vbash $(readlink -f $0) $@"
+fi
+
+log() {
+  echo "$1"
+}
+
 if pidof -o %PPID -x "add-container-images.sh">/dev/null; then
-    echo "add-container-images.sh script is already running"
+    log "add-container-images.sh script is already running"
     exit
 fi
 
@@ -13,21 +21,21 @@ set -e
 pull_image() {
   # shellcheck disable=SC2076
   if [[ ! " ${AVAILABLE_IMAGES[*]} " =~ " ${1} " ]]; then
+    log "Pulling image $1"
     if ! sudo podman pull "$1" > /dev/null 2>&1 ; then
-      echo "Failed to download image $1"
-      exit
+      log "[ERROR] Failed to download image $1"
+      exit 1
     fi
   fi
 }
 
 # shellcheck disable=SC2207
 AVAILABLE_IMAGES=($(run show container image | awk '{ if ( NR > 1  ) { print $1 ":" $2} }'))
-# shellcheck disable=SC2207
-NEW_IMAGES=($(show container name | grep image | uniq | awk '{ print $2}'))
 
-for image in "${NEW_IMAGES[@]}"
+# shellcheck disable=SC2207
+CONFIG_IMAGES=($(show container name | grep image | uniq | awk '{ print $2}'))
+
+for image in "${CONFIG_IMAGES[@]}"
 do
   pull_image "${image}"
 done
-
-exit
