ci: Start testing

diff --git a/.github/workflows/flux-local.yaml b/.github/workflows/flux-local.yaml
--- a/.github/workflows/flux-local.yaml
+++ b/.github/workflows/flux-local.yaml
@@ -21,111 +21,112 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Get Changed Files
+      - name: Get changed files
         id: changed-files
-        uses: tj-actions/changed-files@v45
+        uses: .github/actions/get-changed-files
         with:
-          files: kubernetes/**
+          matchers: |
+            ^kubernetes/.*
 
-  test:
-    if: ${{ needs.filter-changes.outputs.any_changed == 'true' }}
-    name: Flux Local Test
-    runs-on: ubuntu-latest
-    needs:
-      - filter-changes
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # test:
+  #   if: ${{ needs.filter-changes.outputs.any_changed == 'true' }}
+  #   name: Flux Local Test
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - filter-changes
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Run flux-local test
-        uses: docker://ghcr.io/allenporter/flux-local:v7.2.1
-        with:
-          args: test --enable-helm --all-namespaces --path /github/workspace/kubernetes/flux/cluster -v
+  #     - name: Run flux-local test
+  #       uses: docker://ghcr.io/allenporter/flux-local:v7.2.1
+  #       with:
+  #         args: test --enable-helm --all-namespaces --path /github/workspace/kubernetes/flux/cluster -v
 
-  diff:
-    if: ${{ needs.filter-changes.outputs.any_changed == 'true' }}
-    name: Flux Local Diff
-    runs-on: ubuntu-latest
-    needs:
-      - filter-changes
-    permissions:
-      pull-requests: write
-    strategy:
-      matrix:
-        resources:
-          - helmrelease
-          - kustomization
-      max-parallel: 4
-      fail-fast: false
-    steps:
-      - name: Checkout Pull Request Branch
-        uses: actions/checkout@v4
-        with:
-          path: pull
+  # diff:
+  #   if: ${{ needs.filter-changes.outputs.any_changed == 'true' }}
+  #   name: Flux Local Diff
+  #   runs-on: ubuntu-latest
+  #   needs:
+  #     - filter-changes
+  #   permissions:
+  #     pull-requests: write
+  #   strategy:
+  #     matrix:
+  #       resources:
+  #         - helmrelease
+  #         - kustomization
+  #     max-parallel: 4
+  #     fail-fast: false
+  #   steps:
+  #     - name: Checkout Pull Request Branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         path: pull
 
-      - name: Checkout Default Branch
-        uses: actions/checkout@v4
-        with:
-          ref: "${{ github.event.repository.default_branch }}"
-          path: default
+  #     - name: Checkout Default Branch
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: "${{ github.event.repository.default_branch }}"
+  #         path: default
 
-      - name: Run flux-local diff
-        uses: docker://ghcr.io/allenporter/flux-local:v7.2.1
-        with:
-          args: >-
-            diff ${{ matrix.resources }}
-            --unified 6
-            --path /github/workspace/pull/kubernetes/flux/cluster
-            --path-orig /github/workspace/default/kubernetes/flux/cluster
-            --strip-attrs "helm.sh/chart,checksum/config,app.kubernetes.io/version,chart"
-            --limit-bytes 10000
-            --all-namespaces
-            --sources "flux-system"
-            --output-file diff.patch
+  #     - name: Run flux-local diff
+  #       uses: docker://ghcr.io/allenporter/flux-local:v7.2.1
+  #       with:
+  #         args: >-
+  #           diff ${{ matrix.resources }}
+  #           --unified 6
+  #           --path /github/workspace/pull/kubernetes/flux/cluster
+  #           --path-orig /github/workspace/default/kubernetes/flux/cluster
+  #           --strip-attrs "helm.sh/chart,checksum/config,app.kubernetes.io/version,chart"
+  #           --limit-bytes 10000
+  #           --all-namespaces
+  #           --sources "flux-system"
+  #           --output-file diff.patch
 
-      - name: Generate Diff
-        id: diff
-        run: |
-          {
-              echo 'diff<<EOF'
-              cat diff.patch
-              echo EOF
-          } >> "${GITHUB_OUTPUT}";
-          {
-              echo "## Flux ${{ matrix.resources }} diff"
-              echo '```diff'
-              cat diff.patch
-              echo '```'
-          } >> "${GITHUB_STEP_SUMMARY}"
+  #     - name: Generate Diff
+  #       id: diff
+  #       run: |
+  #         {
+  #             echo 'diff<<EOF'
+  #             cat diff.patch
+  #             echo EOF
+  #         } >> "${GITHUB_OUTPUT}";
+  #         {
+  #             echo "## Flux ${{ matrix.resources }} diff"
+  #             echo '```diff'
+  #             cat diff.patch
+  #             echo '```'
+  #         } >> "${GITHUB_STEP_SUMMARY}"
 
-      - name: Generate Token
-        uses: actions/create-github-app-token@v1
-        if: ${{ github.event.pull_request.head.repo.full_name == github.repository && steps.diff.outputs.diff != '' }}
-        id: app-token
-        with:
-          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
-          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
+  #     - name: Generate Token
+  #       uses: actions/create-github-app-token@v1
+  #       if: ${{ github.event.pull_request.head.repo.full_name == github.repository && steps.diff.outputs.diff != '' }}
+  #       id: app-token
+  #       with:
+  #         app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
+  #         private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
 
-      - if: ${{ steps.diff.outputs.diff != '' }}
-        name: Add comment
-        uses: mshick/add-pr-comment@v2
-        with:
-          repo-token: "${{ steps.app-token.outputs.token }}"
-          message-id: "${{ github.event.pull_request.number }}/kubernetes/${{ matrix.resources }}"
-          message-failure: Diff was not successful
-          message: |
-            ```diff
-            ${{ steps.diff.outputs.diff }}
-            ```
+  #     - if: ${{ steps.diff.outputs.diff != '' }}
+  #       name: Add comment
+  #       uses: mshick/add-pr-comment@v2
+  #       with:
+  #         repo-token: "${{ steps.app-token.outputs.token }}"
+  #         message-id: "${{ github.event.pull_request.number }}/kubernetes/${{ matrix.resources }}"
+  #         message-failure: Diff was not successful
+  #         message: |
+  #           ```diff
+  #           ${{ steps.diff.outputs.diff }}
+  #           ```
 
-  flux-local-success:
-    needs:
-      - test
-      - diff
-    if: ${{ !cancelled() }}
-    name: Flux Local successful
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check job status
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
+  # flux-local-success:
+  #   needs:
+  #     - test
+  #     - diff
+  #   if: ${{ !cancelled() }}
+  #   name: Flux Local successful
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check job status
+  #       if: ${{ contains(needs.*.result, 'failure') }}
+  #       run: exit 1
